export * from "./Home/Home"
export * from "./Estudios/Estudios"
export * from "./Nosotros/Nosotros"
export * from "./Contacto/Contacto"
export * from "./FormRegistro/FormRegistro"
export * from "./FromIngresa/FormIngresa"